# Generated by Django 3.0.7 on 2022-05-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_value_percentage', models.FloatField(default=0.0)),
                ('loan_interest_rate_percentage', models.FloatField(default=0.0)),
            ],
        ),
    ]
