# Generated by Django 3.0.7 on 2022-06-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
