# Generated by Django 3.0.7 on 2022-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='addMax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='addMin',
            field=models.FloatField(default=0.0),
        ),
    ]
