# Generated by Django 3.0.7 on 2022-10-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20220620_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='withdraw_commission',
            field=models.FloatField(default=0.0),
        ),
    ]
