# Generated by Django 3.0.7 on 2023-03-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_withdraw_withdraw_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='wallet_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
