# Generated by Django 3.0.7 on 2022-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='paystack_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
