# Generated by Django 3.0.7 on 2022-06-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
