# Generated by Django 3.0.7 on 2022-06-16 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanapplication_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='date_approved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
