# Generated by Django 3.0.7 on 2022-06-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loanapplication_date_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='date_approved',
        ),
    ]
