# Generated by Django 3.0.7 on 2022-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refereeCodeLiteral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
