# Generated by Django 3.0.7 on 2022-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220528_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
