# Generated by Django 3.0.7 on 2022-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bitcoin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
