# Generated by Django 3.0.7 on 2022-06-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_bitcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred',
            field=models.BooleanField(default=False),
        ),
    ]
