# Generated by Django 3.0.7 on 2023-03-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20230307_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
