# Generated by Django 3.0.7 on 2023-03-22 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_delete_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signal_strength',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
