# Generated by Django 3.0.7 on 2023-03-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_traders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traders',
            options={'verbose_name_plural': 'Traders'},
        ),
        migrations.AddField(
            model_name='user',
            name='profit_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
