# Generated by Django 3.0.7 on 2023-03-27 20:06

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20230324_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageId',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.user_image_upload),
        ),
    ]
