# Generated by Django 3.0.7 on 2022-06-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtowallet',
            name='converted_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
