# Generated by Django 3.0.7 on 2022-06-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_currency'),
        ('wallet', '0003_addtowallet_converted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtowallet',
            name='local_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.Currency'),
        ),
    ]
