# Generated by Django 3.0.7 on 2022-06-02 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0004_addtowallet_local_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtowallet',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addtowallet',
            name='type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Referral', 'Referral')], default='Transfer', max_length=50),
        ),
    ]
