# Generated by Django 3.0.7 on 2022-06-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20220602_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Crypto', 'Crypto')], default='Transfer', max_length=50),
        ),
    ]
