# Generated by Django 3.0.7 on 2022-06-14 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20220607_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtowallet',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
