# Generated by Django 3.0.7 on 2022-06-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_currency_buy_rate'),
        ('wallet', '0007_auto_20220614_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtowallet',
            name='local_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.Currency'),
        ),
        migrations.AlterField(
            model_name='addtowallet',
            name='type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Referral', 'Referral'), ('Loan', 'Loan')], default='Transfer', max_length=50),
        ),
    ]
