# Generated by Django 3.0.7 on 2022-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20220615_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
