# Generated by Django 3.0.7 on 2022-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_withdraw_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='type',
            field=models.CharField(choices=[('Local', 'Local'), ('Bitcoin', 'Bitcoin')], default='Transfer', max_length=50),
        ),
    ]
