# Generated by Django 3.0.7 on 2022-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20220620_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
