# Generated by Django 3.0.7 on 2022-06-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_withdraw_confirmed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtowallet',
            name='type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Referral', 'Referral'), ('Loan', 'Loan'), ('Bitcoin', 'Bitcoin')], default='Transfer', max_length=50),
        ),
    ]
