# Generated by Django 3.0.7 on 2022-06-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20220623_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtowallet',
            name='amount',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='wallettransfer',
            name='date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='type',
            field=models.CharField(choices=[('Local', 'Local'), ('Bitcoin', 'Bitcoin')], db_index=True, default='Transfer', max_length=50),
        ),
    ]
