# Generated by Django 3.0.7 on 2022-07-31 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_auto_20220624_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='confirmDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
