# Generated by Django 3.0.7 on 2022-08-15 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0016_withdraw_confirmdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('approved', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ref', models.TextField()),
                ('type', models.CharField(choices=[('Ethereum', 'Ethereum'), ('Bitcoin Cash', 'Bitcoin Cash'), ('Bitcoin', 'Bitcoin')], default='Bitcoin', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
