# Generated by Django 3.0.7 on 2022-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_cryptoadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoadd',
            name='confirmedBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
