# Generated by Django 3.0.7 on 2023-03-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_cryptoadd_confirmedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='type',
            field=models.CharField(choices=[('Local', 'Local'), ('Bitcoin', 'Bitcoin'), ('Bank Transfer', 'Bank Transfer'), ('Paypal', 'Paypal')], db_index=True, default='Transfer', max_length=50),
        ),
    ]
