# Generated by Django 3.0.7 on 2022-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profit_frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
