# Generated by Django 3.0.7 on 2022-05-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20220531_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='package',
            new_name='portfolio',
        ),
    ]
