# Generated by Django 3.0.7 on 2022-05-31 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_auto_20220531_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='last_profit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
