# Generated by Django 3.0.7 on 2022-07-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0010_auto_20220727_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldinvestment',
            name='approvedBy',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
