# Generated by Django 3.0.7 on 2022-07-31 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0013_auto_20220730_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldinvestment',
            name='confirmDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
