# Generated by Django 3.0.7 on 2022-10-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggyvest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggy',
            name='retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='piggy',
            name='stat',
            field=models.IntegerField(default=0),
        ),
    ]
