# Generated by Django 3.0.7 on 2022-10-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggyvest', '0002_auto_20221002_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piggy',
            name='stat',
        ),
    ]
