# Generated by Django 3.0.7 on 2022-10-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggyvest', '0003_remove_piggy_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggy',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
