# Generated by Django 3.0.7 on 2022-10-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggyvest', '0004_piggy_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggy',
            name='incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
